name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🔑
        uses: actions/checkout@v4

      - name: Setup Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies 📥
        run: npm ci

      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          # We don't need to run a local build/start server since Cypress hits a public url (orangehrmlive.com)
          browser: chrome
        env:
          # Cypress base URL can be defined here
          CYPRESS_baseUrl: https://opensource-demo.orangehrmlive.com
